import { ImageToCaptionClient } from "@/components/tools/image-to-caption/client";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

const faqData = [
  {
    question: "What is Flux AI Image To Caption feature?",
    answer: "Flux AI Image To Caption is a tool that generates AI-powered captions for images. It analyzes the content of an uploaded image and creates a descriptive caption that reflects what is depicted."
  },
  {
    question: "Is Flux AI Image To Caption free to use?",
    answer: "Yes, Flux AI Image To Caption is completely free to use. We aim to make AI technology accessible to everyone, allowing you to generate captions for your images without any cost."
  },
  {
    question: "How does Flux AI Image To Caption work?",
    answer: "To use Flux AI Image To Caption, simply upload an image to our platform. The AI will analyze the image and generate a caption that describes its contents. This process is quick and requires no additional input from the user."
  },
  {
    question: "What types of images can I use with Flux AI Image To Caption?",
    answer: "Flux AI Image To Caption supports common image formats such as JPEG, PNG, and GIF. You can upload photos, digital art, screenshots, or any other type of image, and our AI will generate a caption for it."
  },
  {
    question: "Can I use Flux AI Image To Caption for multiple images at once?",
    answer: "Currently, Flux AI Image To Caption only supports uploading and processing one image at a time. You'll need to upload images individually to get a caption for multiple images."
  },
  {
    question: "Can I customize the captions generated by Flux AI Image To Caption?",
    answer: "Flux AI Image To Caption generates captions automatically based on the image content. At this time, there are no customization options available. The AI provides a standard caption for each uploaded image."
  },
  {
    question: "How accurate are the captions from Flux AI Image To Caption?",
    answer: "Flux AI Image To Caption uses advanced AI technology to generate accurate captions. While it's very good at identifying common objects, scenes, and actions, it may not capture every nuance or context. The tool provides a general caption of the main elements in the image."
  },
  {
    question: "What are some uses for Flux AI Image To Caption?",
    answer: "Flux AI Image To Caption can be useful for various purposes, such as generating alt text for website images to improve accessibility, helping with content creation for social media posts, assisting visually impaired individuals in understanding image content, or simply satisfying curiosity about how AI interprets images."
  }
];

export default async function ImageToCaptionPage() {
  return (
    <div className="container mx-auto px-4 py-12 md:px-6">
      {/* Hero Section */}
      <section className="text-center">
        <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
            Image To Caption - Flux AI
        </h1>
        <p className="mx-auto mt-4 max-w-[700px] text-muted-foreground md:text-xl">
            Use AI to generate captions for your images.
        </p>
      </section>

      {/* Client Component */}
      <ImageToCaptionClient />

      {/* FAQ Section */}
      <section className="mt-16">
        <div className="mx-auto max-w-4xl text-center">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">
            Flux AI Frequently asked questions
          </h2>
        </div>
        <div className="mx-auto mt-8 max-w-3xl">
          <Accordion type="single" collapsible className="w-full">
            {faqData.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger>{faq.question}</AccordionTrigger>
                <AccordionContent>{faq.answer}</AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </section>

    </div>
  );
} 